language: node_js

node_js:
  - "10"

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn coveralls

deploy:
  provider: npm
  email: "$EMAIL"
  api_key:
    secure: "$API_KEY"
  on:
    tags: true
    repo: Rocketseat/unform
